//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LRS.NET.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Controls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Controls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LRS.NET.Resources.Controls", typeof(Controls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم مدیریت وام.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه: {0}.
        /// </summary>
        public static string App_Version {
            get {
                return ResourceManager.GetString("App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی.
        /// </summary>
        public static string Button_Copy {
            get {
                return ResourceManager.GetString("Button_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشتن.
        /// </summary>
        public static string Button_Cut {
            get {
                return ResourceManager.GetString("Button_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Button_More {
            get {
                return ResourceManager.GetString("Button_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید.
        /// </summary>
        public static string Button_Ok {
            get {
                return ResourceManager.GetString("Button_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چسباندن.
        /// </summary>
        public static string Button_Paste {
            get {
                return ResourceManager.GetString("Button_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلو.
        /// </summary>
        public static string Button_Redo {
            get {
                return ResourceManager.GetString("Button_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عقب.
        /// </summary>
        public static string Button_Undo {
            get {
                return ResourceManager.GetString("Button_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Label_City_Name {
            get {
                return ResourceManager.GetString("Label_City_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Label_City_Province {
            get {
                return ResourceManager.GetString("Label_City_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _نام.
        /// </summary>
        public static string Label_Country_Name {
            get {
                return ResourceManager.GetString("Label_Country_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Label_Province_Country {
            get {
                return ResourceManager.GetString("Label_Province_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Label_Province_Name {
            get {
                return ResourceManager.GetString("Label_Province_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _درباره....
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Menu_Add {
            get {
                return ResourceManager.GetString("Menu_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _کپی.
        /// </summary>
        public static string Menu_Copy {
            get {
                return ResourceManager.GetString("Menu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _برداشتن.
        /// </summary>
        public static string Menu_Cut {
            get {
                return ResourceManager.GetString("Menu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _اطلاعات.
        /// </summary>
        public static string Menu_Data {
            get {
                return ResourceManager.GetString("Menu_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Menu_Delete {
            get {
                return ResourceManager.GetString("Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Menu_Edit {
            get {
                return ResourceManager.GetString("Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _خروج.
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _کمک.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _چسباندن.
        /// </summary>
        public static string Menu_Paste {
            get {
                return ResourceManager.GetString("Menu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _جلو.
        /// </summary>
        public static string Menu_Redo {
            get {
                return ResourceManager.GetString("Menu_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Menu_Remove {
            get {
                return ResourceManager.GetString("Menu_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _ذخیره.
        /// </summary>
        public static string Menu_Save {
            get {
                return ResourceManager.GetString("Menu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _جستجو.
        /// </summary>
        public static string Menu_Search {
            get {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _انتخاب همه.
        /// </summary>
        public static string Menu_SelectAll {
            get {
                return ResourceManager.GetString("Menu_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _عقب.
        /// </summary>
        public static string Menu_Undo {
            get {
                return ResourceManager.GetString("Menu_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        public static string Shortcut_About {
            get {
                return ResourceManager.GetString("Shortcut_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+C.
        /// </summary>
        public static string Shortcut_Copy {
            get {
                return ResourceManager.GetString("Shortcut_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+X.
        /// </summary>
        public static string Shortcut_Cut {
            get {
                return ResourceManager.GetString("Shortcut_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del.
        /// </summary>
        public static string Shortcut_Delete {
            get {
                return ResourceManager.GetString("Shortcut_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+V.
        /// </summary>
        public static string Shortcut_Paste {
            get {
                return ResourceManager.GetString("Shortcut_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Y.
        /// </summary>
        public static string Shortcut_Redo {
            get {
                return ResourceManager.GetString("Shortcut_Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+S.
        /// </summary>
        public static string Shortcut_Save {
            get {
                return ResourceManager.GetString("Shortcut_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+A.
        /// </summary>
        public static string Shortcut_SelectAll {
            get {
                return ResourceManager.GetString("Shortcut_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl+Z.
        /// </summary>
        public static string Shortcut_Undo {
            get {
                return ResourceManager.GetString("Shortcut_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهرها.
        /// </summary>
        public static string Window_City {
            get {
                return ResourceManager.GetString("Window_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشورها.
        /// </summary>
        public static string Window_Country {
            get {
                return ResourceManager.GetString("Window_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور مورد نظر....
        /// </summary>
        public static string Window_Country_Selector {
            get {
                return ResourceManager.GetString("Window_Country_Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنجره اصلی.
        /// </summary>
        public static string Window_Main {
            get {
                return ResourceManager.GetString("Window_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان‌ها.
        /// </summary>
        public static string Window_Province {
            get {
                return ResourceManager.GetString("Window_Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان مورد نظر....
        /// </summary>
        public static string Window_Province_Selector {
            get {
                return ResourceManager.GetString("Window_Province_Selector", resourceCulture);
            }
        }
    }
}
